site_name: Welltrack
site_dir: build/site
# extra_css:
#   - assets/extra.css
repo_url: https://github.com/wuxxin/welltrack
edit_uri: blob/main
theme:
  name: mkdocs
  language: de
  navigation_depth: 3
  # palette:
  #   primary: deep purple
  logo: assets/icon-192.png
  favicon: assets/icon-192.png
  # features:
  #   - header.integrate
  #   - navigation.tabs
  #   - navigation.tabs.sticky
  #   - navigation.sections
  #   - navigation.tracking
  #   - toc.follow
nav:
  - Dokumentation: README.md
  - Welltrack-WebApp: welltrack/welltrack.html
  - Daten-Analyse-WebApp: marimo
plugins:
  - marimo
markdown_extensions:
  - smarty
  - toc:
      permalink: "#"
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
